[package]
name = "readchecker"
version = "0.1.0"
authors = ["Ben Booth <benwbooth@gmail.com>"]
edition = "2021"

[dependencies]
sha2 = "*"
bio = "*"
anyhow = "*"
flate2 = "*"
byte-unit = "*"
procfs = "*"
dashmap = "*"
rayon = "*"
atomic-counter = "*"
generic-array = "*"
csv = "*"